services:
  giropops-senhas:
    build: ./Dockerfile
    ports:
      - "5000:5000"
    networks:
      - giropops
    environment:
      REDIS_HOST: redis
    volumes:
      - strigus:/strigus
    deploy:
      resources:
        reservations:
          cpu: '0.25'
          memory: 128M
        limits:
          cpu: '0.5'
          memory: 256M
  redis:
    image: redis
    networks:
      - giropops
    volumes:
      - strigus:/strigus

networks:
  giropops:
    driver: bridge
volumes:
  strigus:
